#cloud-config

NoCloud:
  meta-data:
    instance-id: ${server_name}
    local-hostname: ${server_name}

# Host
preserve_hostname: False
hostname: ${server_name}
fqdn: ${server_name}.local
 
# Creat user
users:
    - name: ${username}
      lock_passwd: False
      groups: wheel
      shell: /bin/bash
      sudo: ALL=(ALL) NOPASSWD:ALL
      ssh-authorized-keys:
        - ${ssh-key}
 
# Configure where output will go
output:
  all: ">> /var/log/cloud-init.log"
 
# configure interaction with ssh server
ssh_genkeytypes: ['ed25519', 'rsa']
 
# set timezone for VM
timezone: Europe/Oslo
 
runcmd:
  - snap remove lxd
  - touch /etc/cloud/cloud-init.disabled
  - apt update

growpart:
  mode: auto
  devices: ['/']
