- hosts: "localhost"

  vars:
    project_dir: "/home/{{ ansible_user_id }}/kvm-servers"
    images:
      - https://cloud-images.ubuntu.com/daily/server/focal/current/focal-server-cloudimg-amd64-disk-kvm.img
      - https://cloud-images.ubuntu.com/daily/server/jammy/current/jammy-server-cloudimg-amd64-disk-kvm.img
  tasks:
  - name: Create image directory
    file: path={{ project_dir }}/images state=directory

  - name: Start kvm images web server
    docker_container:
      name: kvm-images
      image: nginx:latest
      container_default_behavior: no_defaults
      state: started
      ports:
      - "8080:80"
      volumes:
      - "{{ project_dir }}/images:/usr/share/nginx/html/images:ro"
      - "{{ project_dir }}/files/nginx.conf:/etc/nginx/conf.d/default.conf:ro"

  - name: Register existing images
    stat: path={{ project_dir }}/images/{{ item | basename }}
    register: images_results
    with_items: "{{ images }}"

  - name: Pull images
    get_url:
      url: "{{ item.item }}"
      dest: "{{ project_dir }}/images"
    with_items: "{{ images_results.results }}"
    when: not item.stat.exists

  - name: Update images
    get_url:
      url: "{{ item }}"
      dest: "{{ project_dir }}/images"
    with_items: "{{ images }}"
    when: update_images|default(false)|bool == true
